DROP TABLE IF EXISTS tasks;

CREATE TABLE tasks (
   id BIGINT IDENTITY PRIMARY KEY,
   title VARCHAR(255) NOT NULL,
   description TEXT,
   status VARCHAR(50) NOT NULL,
   created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
